pub mod app;
pub mod arrange;
pub mod articulation_commands;
pub mod audio_settings;
pub mod automation;
pub mod browser;
pub mod command_router;
pub mod diagnostics;
pub mod editing_commands;
pub mod editor;
pub mod gpu_canvas;
#[cfg(feature = "slint-wgpu")]
pub mod slint_wgpu;
#[cfg(feature = "gpu-canvas")]
pub mod wgpu_canvas;
#[cfg(feature = "egui-canvas")]
pub mod egui_canvas;
pub mod midi;
pub mod midi_commands;
pub mod misc;
pub mod mixer;
pub mod operation_gate;
pub mod plugin;
pub mod plugin_commands;
pub mod plugin_polling;
pub mod plugin_telemetry;
pub mod project;
pub mod project_commands;
pub mod recording;
pub mod recording_commands;
pub mod recovery;
pub mod render;
pub mod render_inspector;
#[cfg(debug_assertions)]
pub mod smoke;
pub mod special_commands;
pub mod stack;
pub mod sync;
pub mod telemetry;
pub mod telemetry_analysis;
pub mod telemetry_loop;
pub mod telemetry_render;
pub mod telemetry_video;
pub mod templates;
pub mod tempo;
pub mod timeline;
pub mod track_model;
pub mod transport;
pub mod ui_contract;
