#pragma once

#include <vector>
#include <complex>
#include <cmath>
#include <algorithm>
#include <array>
#include <atomic>
#include "fft_engine.hpp"

namespace Aura::DSP::Analysis {

/**
 * @class SpectralEditor
 * @brief Industrial Surgical Repair Engine (Sovereign Cinema Pro).
 * Features Windowed OLA (OverLap-Add) for artifact-free editing.
 * HONEST FIX: Implements RT-Safe OLA with zero heap allocations during process.
 */
class SpectralEditor {
public:
    static constexpr uint32_t kMaxFFTSize = 4096;
    
    SpectralEditor(uint32_t fftSize = 2048) 
        : m_fftSize(normalizeFftSize(fftSize)),
          m_fftEngine(m_fftSize) {
        m_hopSize = std::max<uint32_t>(1u, m_fftSize / 4); // 75% overlap

        m_complexBuffer.resize(m_fftSize);
        m_window.resize(m_fftSize);
        // `process()` accepts blocks up to the accumulator capacity (4x the
        // FFT size). Keep the full host block until all newly available
        // analysis frames have been rendered; the old 2x buffer dropped the
        // tail of a large offline block before STFT could see it.
        m_analysisBuffer.resize(m_fftSize * 4, 0.0f);
        m_accumBuffer.resize(m_fftSize * 4, 0.0f);
        m_normBuffer.resize(m_fftSize * 4, 0.0f);
        m_noiseProfile.resize(m_fftSize, 0.0f);
        
        // --- Hanning Window for COLA (Constant Overlap-Add) ---
        for (uint32_t i = 0; i < m_fftSize; ++i) {
            m_window[i] = 0.5f * (1.0f - std::cos(2.0f * M_PI * i / (m_fftSize - 1)));
        }
    }

    /**
     * @brief PROCESS: RT-Safe Overlap-Add Spectral Processing.
     */
    void process(const float* input, float* output, uint32_t len) {
        if (!input || !output || len == 0 || len > m_accumBuffer.size()) return;
        if (m_clearNoiseProfile.exchange(false, std::memory_order_relaxed)) {
            std::fill(m_noiseProfile.begin(), m_noiseProfile.end(), 0.0f);
            m_noiseLearnFrames.store(0, std::memory_order_relaxed);
        }
        // Queue input before rendering the newly available OLA frames.  The
        // previous ordering emitted/shifted the accumulator first, so a host
        // block at least as large as the FFT window discarded the frame it
        // had just produced.  That made offline renders silently lose audio
        // while smaller realtime blocks appeared to work by accident.
        for (uint32_t i = 0; i < len; ++i) {
            // 1. Shift into analysis buffer
            if (m_writePos < m_analysisBuffer.size()) {
                m_analysisBuffer[m_writePos++] = input[i];
            }
        }

        // 3. Perform STFT if we have enough hop
        while (m_writePos >= m_fftSize) {
            // Apply Window (In-place if possible, but we need a temporary for FFT)
            // HONEST FIX: Using a pre-allocated scratch buffer for FFT
            for (uint32_t i = 0; i < m_fftSize; ++i) {
                m_windowedScratch[i] = m_analysisBuffer[i] * m_window[i];
            }

            // Time -> Freq
            m_fftEngine.forward(m_windowedScratch, m_complexBuffer);

            // --- SURGICAL ACTIONS ---
            if (m_learnMode.load(std::memory_order_relaxed)) {
                learnNoiseProfile();
            } else if (m_restorationActive.load(std::memory_order_relaxed)) {
                applyDenoise();
            }
            
            if (m_harmonicEraseRequested.load(std::memory_order_relaxed)) {
                applyEraseHarmonics();
            }

            // Freq -> Time
            m_fftEngine.inverse(m_complexBuffer, m_windowedScratch);

            // Overlap-Add into Accumulator
            for (uint32_t i = 0; i < m_fftSize; ++i) {
                const float window = m_window[i];
                m_accumBuffer[i] += m_windowedScratch[i] * window;
                m_normBuffer[i] += window * window;
            }

            // Shift analysis buffer by hopSize
            std::copy(m_analysisBuffer.begin() + m_hopSize, m_analysisBuffer.begin() + m_writePos, m_analysisBuffer.begin());
            m_writePos -= m_hopSize;
        }

        // Extract after STFT processing so frames generated by this call are
        // observable even when `len >= m_fftSize`.
        for (uint32_t i = 0; i < len; ++i) {
            const float norm = m_normBuffer[i];
            output[i] = (std::isfinite(m_accumBuffer[i]) && norm > 1.0e-6f)
                ? m_accumBuffer[i] / norm : 0.0f;
        }

        // Shift accumulator by processed length
        std::copy(m_accumBuffer.begin() + len, m_accumBuffer.end(), m_accumBuffer.begin());
        std::fill(m_accumBuffer.end() - len, m_accumBuffer.end(), 0.0f);
        std::copy(m_normBuffer.begin() + len, m_normBuffer.end(), m_normBuffer.begin());
        std::fill(m_normBuffer.end() - len, m_normBuffer.end(), 0.0f);
    }

    uint32_t latencySamples() const noexcept { return m_fftSize; }

    // OLA retains one complete analysis frame plus the hop interval after
    // the final input block.  Expose this separately from algorithmic
    // latency so offline renderers can allocate and flush the full tail.
    uint32_t tailSamples() const noexcept { return m_fftSize + m_hopSize; }

    // Drain the overlap-add tail after the source has ended. This is intended
    // for offline rendering/export; it uses a bounded stack zero block and
    // never allocates on the audio thread.
    void flush(float* output, uint32_t len) {
        if (!output || len == 0) return;
        std::array<float, 256> zeros{};
        uint32_t written = 0;
        while (written < len) {
            const uint32_t chunk = std::min<uint32_t>(
                static_cast<uint32_t>(zeros.size()), len - written);
            process(zeros.data(), output + written, chunk);
            written += chunk;
        }
    }

    void setLearnMode(bool active) {
        m_learnMode.store(active, std::memory_order_relaxed);
        if (active) m_clearNoiseProfile.store(true, std::memory_order_relaxed);
    }
    void clearNoiseProfile() noexcept {
        m_clearNoiseProfile.store(true, std::memory_order_relaxed);
    }
    bool noiseProfileReady() const noexcept { return m_noiseLearnFrames.load(std::memory_order_relaxed) > 0; }
    void setRestorationActive(bool active) { m_restorationActive.store(active, std::memory_order_relaxed); }
    void setDenoiseThreshold(float t) { m_denoiseThreshold.store(std::isfinite(t) ? std::clamp(t, 0.0f, 8.0f) : 1.0f, std::memory_order_relaxed); }
    
    void requestEraseHarmonics(float fund, float sr, float bw) {
        if (!std::isfinite(fund) || !std::isfinite(sr) || !std::isfinite(bw) ||
            fund <= 0.0f || sr <= 100.0f || bw <= 0.0f) {
            m_harmonicEraseRequested.store(false, std::memory_order_relaxed);
            return;
        }
        m_fund.store(fund, std::memory_order_relaxed);
        m_sr.store(sr, std::memory_order_relaxed);
        m_bw.store(bw, std::memory_order_relaxed);
        m_harmonicEraseRequested.store(true, std::memory_order_relaxed);
    }

    void reset() noexcept {
        m_writePos = 0;
        m_learnMode.store(false, std::memory_order_relaxed);
        m_restorationActive.store(false, std::memory_order_relaxed);
        m_clearNoiseProfile.store(false, std::memory_order_relaxed);
        m_harmonicEraseRequested.store(false, std::memory_order_relaxed);
        std::fill(m_analysisBuffer.begin(), m_analysisBuffer.end(), 0.0f);
        std::fill(m_accumBuffer.begin(), m_accumBuffer.end(), 0.0f);
        std::fill(m_normBuffer.begin(), m_normBuffer.end(), 0.0f);
        m_clearNoiseProfile.store(true, std::memory_order_relaxed);
        m_noiseLearnFrames.store(0, std::memory_order_relaxed);
        std::fill(m_complexBuffer.begin(), m_complexBuffer.end(), std::complex<float>{0.0f, 0.0f});
        m_windowedScratch.fill(0.0f);
    }

private:
    static uint32_t normalizeFftSize(uint32_t requested) noexcept {
        requested = std::clamp(requested, 64u, kMaxFFTSize);
        uint32_t size = 64u;
        while (size < requested && size < kMaxFFTSize) size <<= 1u;
        return size;
    }

    void learnNoiseProfile() {
        const uint32_t frame = m_noiseLearnFrames.load(std::memory_order_relaxed);
        const float alpha = 1.0f / static_cast<float>(std::min<uint32_t>(frame + 1u, 64u));
        for (uint32_t i = 0; i < m_fftSize; ++i) {
            float mag = std::abs(m_complexBuffer[i]);
            if (!std::isfinite(mag)) mag = 0.0f;
            m_noiseProfile[i] += (mag - m_noiseProfile[i]) * alpha;
        }
        m_noiseLearnFrames.fetch_add(1u, std::memory_order_relaxed);
    }

    void applyDenoise() {
        for (uint32_t i = 0; i < m_fftSize; ++i) {
            float mag = std::abs(m_complexBuffer[i]);
            const float threshold = m_denoiseThreshold.load(std::memory_order_relaxed);
            float profile = std::isfinite(m_noiseProfile[i]) ? m_noiseProfile[i] * threshold : 0.0f;
            if (mag < profile) {
                m_complexBuffer[i] *= (mag / (profile + 1e-9f)) * 0.1f; // Soft knee suppression
            }
        }
    }

    void applyEraseHarmonics() {
        const float sr = m_sr.load(std::memory_order_relaxed);
        const float fund = m_fund.load(std::memory_order_relaxed);
        const float bw = m_bw.load(std::memory_order_relaxed);
        if (!std::isfinite(sr) || sr <= 0.0f || !std::isfinite(fund) || !std::isfinite(bw)) return;
        float binWidth = sr / m_fftSize;
        for (int h = 1; h < 16; ++h) {
            float f = fund * h;
            if (f > sr / 2) break;
            
            int32_t centerBin = (int32_t)(f / binWidth);
            int32_t widthBins = (int32_t)(bw / binWidth);
            
            for (int32_t b = centerBin - widthBins/2; b <= centerBin + widthBins/2; ++b) {
                if (b >= 0 && (uint32_t)b < m_fftSize) {
                    m_complexBuffer[b] = 0.0f;
                    // Preserve Hermitian symmetry so the inverse FFT remains
                    // real-valued after surgical harmonic removal.
                    const int32_t mirror = static_cast<int32_t>(m_fftSize) - b;
                    if (mirror >= 0 && static_cast<uint32_t>(mirror) < m_fftSize)
                        m_complexBuffer[mirror] = 0.0f;
                }
            }
        }
    }

    uint32_t m_fftSize;
    uint32_t m_hopSize;
    uint32_t m_writePos = 0;
    
    FFTEngine m_fftEngine;
    std::vector<float> m_window;
    std::vector<float> m_analysisBuffer;
    std::vector<std::complex<float>> m_complexBuffer;
    std::vector<float> m_accumBuffer;
    std::vector<float> m_normBuffer;
    std::vector<float> m_noiseProfile;
    std::atomic<uint32_t> m_noiseLearnFrames{0};
    
    std::array<float, kMaxFFTSize> m_windowedScratch{}; // RT-Safe scratch
    
    std::atomic<bool> m_learnMode{false};
    std::atomic<bool> m_restorationActive{false};
    std::atomic<bool> m_clearNoiseProfile{false};
    std::atomic<float> m_denoiseThreshold{1.0f};
    
    std::atomic<bool> m_harmonicEraseRequested{false};
    std::atomic<float> m_fund{0.0f}, m_sr{44100.0f}, m_bw{10.0f};
};

} // namespace Aura::DSP::Analysis
