import { Style } from "../style.slint";
import { Z_Knob } from "../primitives/knob.slint";

export component Z_AuraModular {
    Rectangle {
        width: 100%; height: 400px; background: Style.surface; border_width: 1.5px; border_color: Style.border;
        HorizontalLayout {
            padding: 20px; spacing: 40px;
            VerticalLayout {
                width: 140px; spacing: 10px;
                Text { text: "OSCILLATOR 1"; font-size: 9px; color: Style.brand; font-weight: 900; }
                Rectangle { height: 60px; background: #000; Rectangle { width: 6px; height: 6px; border_radius: 3px; background: Style.brand; x: 130px; y: 27px; } }
                Z_Knob { label: "Frequency"; value: 0.4; unit: " kHz"; display-value: Math.round((0.2 + self.value * 9.8) * 10.0) / 10.0 + " kHz"; }
            }
            Path {
                width: 200px; height: 200px; stroke: Style.brand; stroke_width: 2px;
                MoveTo { x: 0; y: 100; }
                CubicTo { control-1-x: 100.0; control-1-y: 100.0; control-2-x: 100.0; control-2-y: 200.0; x: 200.0; y: 200.0; }
            }
            VerticalLayout {
                width: 140px; spacing: 10px;
                Text { text: "FILTER 1"; font-size: 9px; color: #aaa; font-weight: 900; }
                Rectangle { height: 60px; background: #000; Rectangle { width: 6px; height: 6px; border_radius: 3px; background: #A1A1A6; x: -3px; y: 27px; } }
                Z_Knob { label: "Cutoff"; value: 0.7; unit: " kHz"; display-value: Math.round((0.2 + self.value * 9.8) * 10.0) / 10.0 + " kHz"; }
            }
        }
    }
}
